# Generated by Django 2.1.15 on 2020-10-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('run_extract', models.BooleanField(default=False, verbose_name='Ejecutar extracion')),
                ('run_transform', models.BooleanField(default=False, verbose_name='Ejecutar api')),
                ('status', models.CharField(choices=[('created', 'Creado'), ('extract-running', 'extracion en ejecución'), ('extract-done', 'extracion completado'), ('extract-failure', 'extracion fallido'), ('api-running', 'api en ejecución'), ('api-done', 'api completado'), ('api-failure', 'api fallido')], default='created', max_length=30, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Ejecución',
                'verbose_name_plural': 'Ejecuciones',
            },
        ),
    ]
